#ifndef ARCH_i386_INTERRUPTS_H
#define ARCH_i386_INTERRUPTS_H

#include "../segmentation/gdt.h"

/*
    Assembly routine for properly loading the ldt registers (see load_idt.S)
    Uses the same pointer formatting as the lgdt instruction
*/
extern void load_idt(gdt_ptr_t *ptr);

/*
    Interrupt handles generated by the generic interrupt handles in 'interrupt_handles.S'
*/
void interrupt_handler_0();   // division by zero
void interrupt_handler_14();  // page fault

#endif /* ARCH_i386_INTERRUPTS_H */
